# Generated by Django 5.0.3 on 2024-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="signapp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
    ]
